package com.bat.petra.photorecognition.common.configuration;

public class ApplicationProperty {

    private ApplicationProperty() {}

    public static final String EINSTEIN_VISION_ACCOUNT_ID = "EINSTEIN_VISION_USERNAME";
    public static final String EINSTEIN_VISION_PRIVATE_KEY = "EINSTEIN_VISION_PRIVATE_KEY";
//    public static final String EINSTEIN_VISION_FILENAME = "EINSTEIN_VISION_FILENAME";
    public static final String EINSTEIN_VISION_URL = "EINSTEIN_VISION_URL";
    public static final String EINSTEIN_VISION_ACCESS_TOKEN = "EINSTEIN_VISION_ACCESS_TOKEN";
    public static final String EINSTEIN_VISION_REFRESH_TOKEN = "EINSTEIN_VISION_REFRESH_TOKEN";
    public static final String EINSTEIN_VISION_ACCESS_TOKEN_EXPIRES_IN = "EINSTEIN_VISION_ACCESS_TOKEN_EXPIRES_IN";
    public static final String EINSTEIN_VISION_TIME_DIFFERENCE_LIMIT = "EINSTEIN_VISION_TIME_DIFFERENCE_LIMIT";
    public static final String AZURE_CONTAINER_NAME = "AZURE_CONTAINER_NAME";
    public static final String AZURE_CONNECTION_STRING = "AZURE_CONNECTION_STRING";
    public static final String EINSTEIN_VISION_VALIDATION_TIME_DIFFERENCE_ENABLED = "EINSTEIN_VISION_VALIDATION_TIME_DIFFERENCE_ENABLED";
    public static final String EINSTEIN_VISION_VALIDATION_FACE_DETECTION_ENABLED = "EINSTEIN_VISION_VALIDATION_FACE_DETECTION_ENABLED";
    public static final String EINSTEIN_VISION_MODEL_ID = "EINSTEIN_VISION_MODEL_ID";
    public static final String AZURE_INTEGRATION = "AzureIntegration";
    public static final String EINSTEIN_VISION_FILE_SIZE_LIMIT_MIN = "EINSTEIN_VISION_FILE_SIZE_LIMIT_MIN";
    public static final String EINSTEIN_VISION_FILE_SIZE_LIMIT_MAX = "EINSTEIN_VISION_FILE_SIZE_LIMIT_MAX";
    public static final String EINSTEIN_VISION_FACE_DETECTION_SERVICE_URL = "EINSTEIN_VISION_FACE_DETECTION_SERVICE_URL";
}
