cache:
 paths:
 - /root/.m2/repository

stages:
 - build
 - deploy

build:
 stage: build
 image: maven:3.3.9-jdk-8
 script:
 - mvn clean package
 tags:
 - docker

deploy_prod:
 stage: deploy
 image: ruby:2.3
 script:
 - apt-get update -qy
 - apt-get install -y ruby-dev
 - gem install dpl
 - dpl --provider=heroku --app=bat-petra-photo-recognition --api-key=56eacf1f-9529-4ba0-8f8f-3db3db15e499
 environment:
  name: prod
  url: http://bat-petra-photo-recognition.herokuapp.com
